.gitignore, package-lock.json, package.json, test/index.fuzz.js
Initialize fuzz testing using [jsfuzz](https://gitlab.com/gitlab-org/security-products/analyzers/fuzzers/jsfuzz).
=> Set up fuzzing

CHANGELOG.md, README.md, docs/index.md, index.js, test/index.fuzz.js, test/index.test.js
=> Add escapeAll function and update recipe for spawn/fork/execFile

.github/workflows/analysis.yml, .github/workflows/lint.yml, .github/workflows/test.yml
-  [Code Analysis (`analysis.yml`)](https://github.com/ericcornelissen/shescape/blob/4f82eca2555fa6514377cebd29be11dc9165c940/.github/workflows/analysis.yml):
- Push/PR: Only run when the source code or the configuration for the analysis tool changes.
- Schedule: In case the analysis tool has more rules that it scans for.
- [Lint (`lint.yml`)](https://github.com/ericcornelissen/shescape/blob/main/.github/workflows/lint.yml)
- Push/PR: Only runs when [linted files](https://github.com/ericcornelissen/shescape/blob/4f82eca2555fa6514377cebd29be11dc9165c940/package.json#L20) or dependencies change.
- ~~Schedule~~: does not run on a schedule as, once linted, does not need to be checked again.
- [Automated Releases (`release.yml`)](https://github.com/ericcornelissen/shescape/blob/4f82eca2555fa651 …
=> Focus CI workflows

CHANGELOG.md, README.md, package-lock.json, package.json, rollup.config.js, src/executables.js, src/main.js, test/executables.test.js, test/main.test.js
=> Follow symbolic links when determining the shell to escape for

package-lock.json
Ran `npm audit fix` and committed the result.
=> Clean up dependencies

index.js
Reduce duplication in the source code based on [CodeClimate issues](https://codeclimate.com/github/ericcornelissen/shescape/issues?category=duplication&engine_name%5B%5D=structure&engine_name%5B%5D=duplication).
<details>
<summary>Screenshot (2022-03-09)</summary>
</details>
=> Reduce duplication

CONTRIBUTING.md, index.js, src/executables.js, src/main.js, src/platforms.js, src/unix.js, src/win.js
=> Improve internal JSDoc

CHANGELOG.md, index.js, src/main.js, test/e2e/_macros.cjs, test/unit/main/escape.test.js, test/unit/main/quote.test.js
=> Update e2e test macros, fix boolean shell value bug

.github/workflows/test.yml, CHANGELOG.md, docs/recipes.md, src/main.js, src/unix.js, src/win.js, test/e2e/child_process.test.js, test/fixtures/unix.cjs, test/fixtures/win.cjs, test/fuzz/_common.cjs, test/fuzz/execFile.test.cjs, test/fuzz/fork.test.cjs, test/fuzz/spawn.test.cjs, test/integration/_macros.cjs, test/unit/_macros.js, test/unit/main/_macros.js, test/unit/main/escape.test.js, test/unit/main/quote.test.js, test/unit/unix/escape.test.js, test/unit/win/escape.test.js
=> Fix excessive escaping of quote characters

src/main.js, test/unit/main/escape.test.js
=> Improve internal usage of the `interpolation` and `quoted` options

CHANGELOG.md, src/win.js, test/fixtures/win.cjs, test/unit/_macros.js
Closes #320 
Fuzzing for this depends on #318
=> Escaping for PowerShell after whitespace with `{interpolation:true}`

.github/workflows/analysis.yml, .github/workflows/lint.yml
=> Update shell-linting and gitleaks CI jobs

.eslintrc.yml, src/executables.js
Based on https://github.com/gajus/eslint-plugin-jsdoc/pull/906#issuecomment-1226346835
=> Lint JSDoc for throws without type

package.json
[Relevant documentation](https://eslint.org/docs/latest/user-guide/configuring/rules#report-unused-eslint-disable-comments)
=> Check for unused ESLint disable directives

.github/workflows/release.yml
=> Remove dependency on `dawidd6/action-get-tag`

CHANGELOG.md, src/unix.js, src/win.js
For clarity and a slight performance improve
=> Refactor replacements

CHANGELOG.md, index.js, package-lock.json, package.json
Release for https://github.com/ericcornelissen/shescape/security/advisories/GHSA-cr84-xvw4-qx3c
=> New patch release

src/main.js
=> Refactor `main.js` to be explicit about parameters

src/platforms.js
=> Refactor `platforms.js` to be more explicit about args

.github/workflows/checks.yml
Add human-readable names to CI job steps that were missing them
=> Add missing names to CI job steps

.github/workflows/configs.yml, script/validate-codecov-config.sh
- Don't run unnecessarily.
- Avoid unexpected failures on `main` due to flakiness.
- Run if related scripts change.
- Improve scripts
=> Update continuous configuration validation

CHANGELOG.md, index.d.ts
=> Improve project's type definitions

package-lock.json
Per https://github.com/ericcornelissen/shescape/actions/runs/3644889478/jobs/6154552845
=> bump (transitive dependency) simple-git from v3.7.1 to v3.15.1

.github/workflows/checks.yml, .github/workflows/configs.yml, .github/workflows/fuzz-matrix.js, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/reusable-audit.yml, .github/workflows/reusable-fuzz.yml
=> Bump CI runner images to latest

.github/workflows/checks.yml, package.json
=> Ensure all vetting tools are always run in the CI

CHANGELOG.md, index.d.ts, index.js
Relates to #160 
Add at least one example per Shescape API function in an effort to make it easier to use Shescape correctly.
=> Add per-API function usage examples

README.md, docs/tips.md
Create documentation with tips/Dos-and-Don'ts for protecting against shell injection besides using Shescape.
=> Document tips for shell protection

.github/workflows/checks.yml
=> Use `failure() || success()` for linting and vetting in CI

.github/dependabot.yml
Reduce number of Dependabot PRs active at any time from 4 to 2.
=> Reconfigure Dependabot

.github/workflows/publish.yml
Based on the run of this workflow for: 4fe9b2720967f87101bdab3967904bff1cd67cd8
=> Configure harder-runner egress-policy for `publish.yml`

.github/workflows/nightly.yml
=> Set up harden runner for nightly tooling updates

test/_arbitraries.js, test/integration/escape-all.test.js, test/integration/escape.test.js, test/integration/quote-all.test.js, test/integration/quote.test.js
Improve the integration tests for this project based on inspiration from [this article on "Methamorphic Testing"](https://www.hillelwayne.com/post/metamorphic-testing/). Additional improvements as a result of having another look at the tests.
=> Improve integration tests

.shellcheckrc, package.json
Relates to #392
Create a ShellCheck configuration file and move CLI configurations from `package.json` into the configuration file.
=> Create ShellCheck configuration file

test/e2e/child_process.test.js, test/unit/unix/escape.test.js
Refactor tests to make them a bit more maintainable.
=> Improve test maintainability

.github/workflows/checks.yml
Relates to #317
Remove unused endpoints from the CI egress policy.
=> Update CI egress policy

.github/workflows/checks.yml
Add a new SAST scan with [Semgrep](https://semgrep.dev). This scan is configured similarly to CodeQL.
=> Set up continuous SAST with Semgrep

.github/workflows/checks.yml
Add a new CI job that runs the SAST tool [DevSkim (GitHub Action)](https://github.com/microsoft/DevSkim-Action) ([DevSkim](https://github.com/Microsoft/DevSkim)), a tool by Microsoft that:
> [...] is a security linter that highlights common security issues in source code.
=> Set up continuous SAST with DevSkim

.github/workflows/labeler.yml
Relates to #797, #798, #801
Try to configure it to not remove pre-assigned labels (again, see #801)
=> Update the "Labeler / Label" job

.github/workflows/ossf.yml
Relates to #802, #804
Update the "OSSF / Scorecard" following a [failed run](https://github.com/ericcornelissen/shescape/actions/runs/4658036956) on the `main` branch.
=> Update "OSSF / Scorecard" job configuration

.github/workflows/ossf.yml
Relates to #804
Fix ports in the "OSSF / Scorecard" job egress policy.
=> Update egress policy for "OSSF / Scorecard" job

test/bench/bench.js
Relates to #125, #659, #870
Add Csh to the benchmark suite.
=> Add benchmark for Csh

index.d.ts
Complements #908
Add `@since` to the documentation for API options.
=> Add `@since` information for API options

package-lock.json
Relates to #819
Try out `npm update` to update transitive dependencies. Followed by `npm dedupe` as an optimization.
=> Update transitive (dev)dependencies

src/unix/bash.js, src/unix/csh.js, src/unix/dash.js, src/unix/zsh.js, src/win/cmd.js, src/win/powershell.js
Relates to #908
Order functions and rename for clarity and readability. In particular, align function names and order/group functions of related functionality.
=> Re-order functions in platform-specific modules

src/main.js, src/reflection.js, testing.js
... since it's reflection functionality. Also allows for deduplicating code with `./testing.js`
=> Move `checkedToString` to the reflection module

.depcheckrc.yml, .github/workflows/checks.yml, CONTRIBUTING.md, package-lock.json, package.json, stryker.integration.config.js, stryker.unit.config.js
Enable stryker ava using the tap runner
=> Use tap-runner for mutation testing

src/unix/bash.js, src/unix/csh.js, src/unix/dash.js, src/unix/zsh.js, test/e2e/_macros.js, test/fuzz/_common.cjs, test/unit/win/index.test.js
Small patch removing all unnecessary usages of string literals I could find from the code base.
=> Don't unnecessarily use string literals

README.md
Relates to #982
Update [the list of features](https://github.com/ericcornelissen/shescape/tree/e953cfca86a8b60e390cae5c001451ee16a76355#features) to explicitly include protection against environment variable access.
=> List environment variable access protection as a library feature

docs/tips.md
Add a new (Node.js-specific) tip on what `child_process` functions to use, as well as how, to reduce the risk of shell injection.
=> Add new tip: use specific `child_process` functions

docs/tips.md
Relates to #1012
Align documentation throughout this project by consistently using title case for all titles.
=> Use title case for all documentation titles

.nsprc, package-lock.json
Relates to #997
Bump transitive dependency semver in order to unignore GHSA-c2qf-rxjj-qqgw.
=> Bump transitive dependency semver

CONTRIBUTING.md, package-lock.json, package.json, script/fuzz.js
Improve the experience of fuzzing this library by:
- Adding a npm command to generate a fuzz coverage command so that someone fuzzing this project can generate a coverage report to identify missed branches or other weak points of the fuzz targets.
- Include `--fuzzTime` argument in the fuzz script help text.
=> Improve fuzzing experience

.github/workflows/checks.yml, bench/bench.js
Relates to #1067
Update the `Check / Benchmark` job to avoid permission errors.
=> Avoid permission errors for benchmark job

test/_runners.cjs, test/e2e/_macros.js, test/fuzz/exec.test.cjs
Relates to #963, #1067
Minor refactoring to the e2e (including fuzz) tests for readability and maintainability.
=> Refactor e2e tests utilities

test/integration/escape-all.test.js, test/integration/escape.test.js, test/integration/quote-all.test.js, test/integration/quote.test.js, test/unit/testing/stubscape.test.js
Improve the assertions of throwing in tests in accordance with the test level: 
- Unit tests should assert the type and error message.
- Integration tests should assert the type (to be in-line with the documented type).
=> Update throws assertions in line with the test level

src/executables.js, src/options.js, src/unix.js, src/win.js
Relates to #1142
Align internal docs for environment variable arguments.
=> Update internal docs

.github/workflows/audit-dev.yml, .github/workflows/audit-release.yml, .github/workflows/checks.yml, .github/workflows/config-codecov.yml, .github/workflows/config-npm.yml, .github/workflows/fuzz-bash.yml, .github/workflows/fuzz-cmd.yml, .github/workflows/fuzz-csh.yml, .github/workflows/fuzz-dash.yml, .github/workflows/fuzz-no-shell.yml, .github/workflows/fuzz-powershell.yml, .github/workflows/fuzz-zsh.yml, .github/workflows/publish.yml, .github/workflows/secrets.yml, .github/workflows/semgrep.yml, CHANGELOG.md, CONTRIBUTING.md, SECURITY.md, index.js, package-lock.json, package.json, script/release/bump-changelog.js
This Pull Request was created manually because [the automated release job](https://github.com/ericcornelissen/shescape/actions/runs/6110503329) failed as a result of the changes of #1160.
---
_It will take a few minutes for this to happen._
[npm]: https://www.npmjs.com/package/shescape
[semantic versioning]: https://semver.org/spec/v2.0.0.html
=> Release v2.0.0

CONTRIBUTING.md, RELEASE.md
Relates to aaaea00fc8f721c81462d03b0ad61cc5f20f9508
Minor fixes for mistakes made in the initialization of the maintenance branch for v1.
=> v1 maintenance branch corrections

.nsprc, package-lock.json
Relates to #1217
Bump transitive dependency `zod` to resolve GHSA-m95q-7qp3-xv42
=> Bump transitive dependency `zod`

CONTRIBUTING.md
Did a pass through the Contributing Guidelines in order to find typos, outdated information, poorly worded/explained concepts, or duplicated copy - and fix them.
=> Improve the Contributing Guidelines

script/hooks/pre-commit, script/hooks/pre-push
Relates to #128
Update git hooks as defined with [husky](https://typicode.github.io/husky/) so that:
- different hooks check similar things
- command ordering makes more semantic sense
=> Align git hooks and order checks

package-lock.json, package.json, test/breakage/stateless.test.js
=> Enable breakage tests for `shescape/stateless`

CONTRIBUTING.md
=> Cover runtime dependency compat testing in Contributing Guidelines

docs/testing.md
Relates to #1149, #1530
Update the testing docs to include a list of available stubs.
=> List available test stubs in the documentation

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, docs/testing.md, test/_arbitraries.js, test/_echo.js, test/unit/_macros.js
Update natural language text to use EN-us spelling.
=> Normalize natural language spelling

.github/workflows/trusty.yml
Try out [`stacklok/trusty-action`](https://github.com/stacklok/trusty-action) ([marketplace](https://github.com/marketplace/actions/trusty-dependency-risk-action)).
=> Try out `stacklok/trusty-action`

.nsprc
Relates to [Audit / npm (#1083)](https://github.com/ericcornelissen/shescape/actions/runs/10786659067), https://github.com/sinonjs/nise/pull/226
=> Ignore GHSA-9wv6-86v2-598j

.github/workflows/fuzz-bash.yml, .github/workflows/fuzz-cmd.yml, .github/workflows/fuzz-csh.yml, .github/workflows/fuzz-dash.yml, .github/workflows/fuzz-no-shell-unix.yml, .github/workflows/fuzz-no-shell-win.yml, .github/workflows/fuzz-powershell.yml, .github/workflows/fuzz-zsh.yml
Since the project isn't seeing much active developed and results have been stable for a while now, I feel like these don't have to fuzzed daily anymore - mostly motivated by reducing resource usage.
=> Reduce fuzzing to monthly

.ndmrc, package-lock.json
=> Update `@vercel/nft@0.27.9` to resolve deprecations

.github/codeql.yml
Try out the CodeQL queries developed by the community (for JavaScript) on this project. These were announced in:
<https://github.blog/security/vulnerability-research/announcing-codeql-community-packs/>
=> Try out the CodeQL community queries for JavaScript

.gitattributes, .gitignore, .npmignore, .npmrc, .tool-versions
=> Expand 'Configuration file for ...' comments

.github/workflows/audit-release.yml
Closes #1826
Relates to [`audit-release.yml` run #570](https://github.com/ericcornelissen/shescape/actions/runs/14074911329)
=> Update continuous auditing of releases

docs/api.md, docs/recipes.md
Relates to #1966, #1968, #1971
=> Add note about DEP0190 to the documentation

package-lock.json, package.json, test/breakage/index.test.js, test/breakage/stateless.test.js
=> Include BusyBox in breakage tests

.github/workflows/audit-release.yml
Relates to #2045, [Audit (release) job #666](https://github.com/ericcornelissen/shescape/actions/runs/15917749457)
=> Disable actions checksum check for release audit job

docs/migration.md, docs/use-cases.md
Relates to #1361, #2028, #2030
=> Add missing "open an issue" links to docs

.ndmrc, package-lock.json
=> Bump transitive dependencies

.github/workflows/audit-release.yml, .github/workflows/gha.sum, .github/workflows/weekly.yml, test/_arbitraries.js
=> Set up weekly updating of transitive dependencies

.github/dependabot.yml
Relates to #2171, [`weekly.yml` job #1](https://github.com/ericcornelissen/shescape/actions/runs/17880521492)
=> Instantiate 2 day cooldown for dependency updates

.github/actions/ghasum/action.yml, .github/workflows/checks.yml, .github/workflows/ghasum.yml
=> Update `ghasum` action

.deepsource.toml
Try out [deepsource](https://deepsource.com/) which seems to require adding a configuration file :unamused: (can't believe you must have a config file...)
=> Try deepsource

config/eslint.js, test/e2e/_macros.js, test/fuzz/_common.js, test/integration/escape-all/no-shell.test.js, test/integration/escape/no-shell.test.js, test/unit/unix/index.test.js, test/unit/win/index.test.js
=> Refactor based on deepsource analysis
