- CHANGELOG.md
- README.md
- docs/_config.yml
- docs/index.md
- package.json
Hosted from the `docs/` directory, keeping it separate from the `README.md` in the root. The rationale behind this is that the website is for users of the packages and the README for potential contributors and, of course, users as well since NPM displays the README on [the package page](https://www.npmjs.com/package/shescape).
> Set up a website for documentation

- docs/index.md
- index.js
- test/index.test.js
Update `quoteAll` to return an array-ified value if the input is not an array.
This change is not backwards compatible and will be included in the same release as #6
> Create array on non-array input in quoteAll

- .github/workflows/test.yml
- README.md
- stryker.config.json
Add "dashboard" reporter to Stryker configuration to use the [online Stryker dashboard](https://dashboard.stryker-mutator.io).
For documentation, see: https://stryker-mutator.io/docs/General/dashboard
For a preview of the dashboard, see: https://dashboard.stryker-mutator.io/reports/github.com/ericcornelissen/shescape/online-mutation-report (the dashboard for this branch of this repo)
- The dashboard reporter won't try to do anything on your local system (unless configured to simulate a CI system), it will only output:
```
INFO DashboardReporter The report was not send to the dashboard. The dashboard.project and/or dashboard.version values were missing and not detected to be running on a build server.
```
- If the `env.STRYKER_DASHBOARD_API_KEY` value is not explicitly set in the step …
> Start using the online Stryker dashboard

- .github/codeql.yml
- .github/workflows/analysis.yml
- Include [`./index.js`](https://github.com/ericcornelissen/shescape/blob/3ebef442a90b78350df38edf11077a1b19e8e8fc/index.js) in the CodeQL analysis.
- Run CodeQL analysis on all branches (and PRs into any branch).
- Following this warning from CodeQL outputted by [`github/codeql-action/init@v1.0.24`](https://github.com/ericcornelissen/shescape/blob/3ebef442a90b78350df38edf11077a1b19e8e8fc/.github/workflows/analysis.yml#L29-L33), don't filter by paths `on: push`.
> Update CodeQL configuration

- script/hooks/common.sh
- script/hooks/pre-commit
- script/hooks/pre-push
:heavy_check_mark: Prevent restoring stashes if non were created.
:heavy_check_mark: Don't stash if there's a merge in progress.
:heavy_check_mark: Maintain index (staged/unstaged) of files when popping stashes.
:heavy_check_mark: Use full names for flags/options to improve readability.
> Improve git hooks

- .github/dependabot.yml
For more information, see [the documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot).
> Enable dependabot updates for GitHub Actions actions

- CHANGELOG.md
- src/main.js
- test/main.test.js
> Ensure argument's `toString` method returns a string

- CHANGELOG.md
- src/win.js
- test/win.prop.js
- test/win.test.js
Based on: https://nodejs.org/api/child_process.html#default-windows-shell
---
> Fix default shell for Windows

- .github/workflows/release.yml
Fixing a mistake made in #185, the `fetch-depth` option should be set on `actions/checkout` not `ericcornelissen/git-tag-annotation-action` (as per [the latter's documentation](https://github.com/ericcornelissen/git-tag-annotation-action#full-example)).
> Fix usage of `fetch-depth` in release workflow

- test/win.prop.js
Add a new property test for [the `getDefaultShell` of the win module](https://github.com/ericcornelissen/shescape/blob/0324efd8838c132f1a929376e4832853b3534008/src/win.js#L119-L125) that aims to test that it always returns a string given the `process.env` object. The `process.env` object is modeled as a specialized instance of [the `fc.object` arbitrary](https://github.com/dubzzz/fast-check/blob/40fdb4bc5c2edcb7773aafbf3afc90882c2db8f3/documentation/Arbitraries.md#object) based on [the official Node.js `process.env` documentation](https://nodejs.org/api/process.html#processenv).
> Improve win::getDefaultShell property tests

- .github/workflows/test.yml
- CHANGELOG.md
- src/win.js
- test/index.test.cjs
> Use `path.win32` from "path" over importing from "path/win32"

- index.js
- src/platforms.js
- test/index.test.js
- test/platform.prop.js
- test/platforms.test.js
... such that it no longer expects as input the `process` object, but rather the environment variables directly. This takes away the assumption/requirement that the environment variables must come from the `process` object. This makes it easier to change where the environment variables come from later, as well as simplifies the function signature for testing.
> Refactor `platforms.js`

- .github/codecov.yml
- .github/workflows/test.yml
Expand to use of coverage reports in the CI to include e2e tests, property tests, and compatibility tests. Given that commands for this are already available, it's simple and convenient to provide the coverage results in the CI as well.
Also add the coverage reports of e2e tests and property tests to Codecov. For e2e tests the coverage report is uploaded per-os. The coverage reports for unit tests, e2e tests, and property tests are separated in Codecov using ["flags"](https://docs.codecov.com/docs/flags).
Compatibility tests are **not** being uploaded to Codecov yet. At the time of creating this Pull Request this seems unnecessary.
> Expand use of coverage in CI

- test/fuzz/fork.test.cjs
Unfortunately, due to a known bug, the fuzz target is currently disabled as it will just find the known bug. See #275 and #286
> Create fuzz target for `child_process.fork`

- package-lock.json
- package.json
- test/prop/index/escape-all.test.js
- test/prop/index/escape.test.js
- test/prop/index/quote-all.test.js
- test/prop/index/quote.test.js
- test/prop/platforms/get-helpers.test.js
- test/prop/unix/default-shell.test.js
- test/prop/unix/escape.test.js
- test/prop/unix/quote.test.js
- test/prop/unix/shell-name.test.js
- test/prop/win/default-shell.test.js
- test/prop/win/escape.test.js
- test/prop/win/quote.test.js
- test/prop/win/shell-name.test.js
Per the deprecation warning for [ava-fast-check](https://www.npmjs.com/package/ava-fast-check):
Replaced by @fast-check/ava
> Replace ava-fast-check by @fast-check/ava

- .github/workflows/test.yml
- test/fuzz/fork.test.cjs
Follow up on #310 to enable fuzzing of `child_process.fork` in the CI. In #310 it was originally enabled (as it fixed a bug that caused the `fork` fuzz target to always crash prior to 5 minutes of running), but then disabled again because of seeming flakiness on Windows. When fuzzing on Windows, with either `cmd.exe` or `powershell.exe`, something like the following error (example) was observed:
```
...
#3266 PULSE     cov: 332 corp: 47 exec/s: 0 rss: 64.16 MB
^
=================================================================
Error: spawn UNKNOWN
Error: spawn UNKNOWN
at ChildProcess.spawn (node:internal/child_process:413:11)
at ChildProcess.spawn (node:internal/child_process:413:11)
at spawn (node:child_process:689:9)
at spawn (node:child_process:689:9)
at fork …
```
> Add fuzzing of `child_process.fork` to fuzz job

- CHANGELOG.md
- src/unix.js
- test/fixtures/unix.cjs
- test/unit/_macros.js
Closes #323 
Fuzzing for this requires #318, hence fuzzing will be taken care of after this is merged into `main`
> Escaping for Unix shells after whitespace with `{interpolation:true}`

- CHANGELOG.md
- src/unix.js
- test/fixtures/unix.cjs
Following up on #272, remove another unnecessary escaping for Dash that was inherited from Bash since Dash doesn't do curly brace expansion.
> Removely curly brace escaping for Dash

- .github/workflows/reusable-fuzz.yml
- README.md
- script/hooks/common.sh
- src/executables.js
- test/e2e/_macros.js
- test/fuzz/exec-file.test.cjs
> **Note**: The fuzz job for `execFile`/`exec-file` ([example](https://github.com/ericcornelissen/shescape/runs/7599576533)) will keep failing until this is merged because it references a re-usable workflow on the `main` branch which specifies the fuzz target "execFile", but this Pull Request changes the name of that fuzz target to "exec-file" (and updates the re-usable workflow accordingly).
> Fixes for issues detected by Codacy

- .github/workflows/analysis.yml
> Update harden-runner configuration

- RELEASE.md
Primarily adjust it so that it asks the releaser to create a release branch and release Pull Request, avoiding pushes to the `main` branch. Also some additional minor but related changes.
> Update manual release guidelines

- .github/workflows/checks.yml
- stryker.config.json
Leverage [Stryker's incremental mode](https://stryker-mutator.io/blog/announcing-incremental-mode/#-incremental-mode) to improve the speed of the mutation testing check in the CI.
The speed up is substantial. Given no unit test is changed in a given Pull Request, the duration of the mutation tests in CI drops from [`16m 14s`](https://github.com/ericcornelissen/shescape/actions/runs/3183350563/jobs/5190475601) to [`0m 17s`](https://github.com/ericcornelissen/shescape/actions/runs/3183497538/jobs/5190799491), or about ~1.7% of the original runtime.
Note that by default incremental mode has been disabled because of poor support when using `commandRunner` (but the `--incremental` flag can still be used to enable it). In particular, changes to the unit tests won't be detected by Stryker. So, …
> Use incremental mode for mutation testing in CI

- .github/codecov.yml
- .github/workflows/checks.yml
The ["unit" flag](https://github.com/ericcornelissen/shescape/blob/836689791c0b8c7c9537982d81841de614f4c66d/.github/codecov.yml#L58-L61) isn't working on Codecov - the Codecov webapp suggests the "upload is empty".
This Pull Request is an attempt to fix that.
> Fix Codecov "unit" flag

- .github/workflows/reusable-audit.yml
- CONTRIBUTING.md
- package.json
> Add npm scripts for auditing dependencies for vulnerabilities

- CHANGELOG.md
- src/win.js
- test/fixtures/win.js
- test/fuzz/_common.cjs
> Update Windows escaping for the exact character sequence `\n\r`

- CHANGELOG.md
- src/win.js
- test/fixtures/unix.js
- test/fixtures/win.js
- test/fuzz/_common.cjs
> Correct `\n\r` to `\r\n`

- .github/workflows/reusable-fuzz.yml
updated ci fuzz tests to not use #488 
[https://github.com/ericcornelissen/shescape/issues/488](url)
> updated CI fuzz tests to not use set-output

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/reusable-audit.yml
Closes #454
---
Add monitoring of runtime dependencies in the latest released version of supported major versions.
> Set up auditing of latest released version

- .github/workflows/checks.yml
- script/check-runtime-deps.js
Relates to #482
---
Create a script that, for each runtime dependency, checks that the installed version is the same as the minimum supported version. Having this guarantee on installed runtime dependencies guarantees that the library is actually compatible with the lowest version it claims to be compatible with.
> Create script to check runtime dependency versions

- .github/workflows/reusable-fuzz.yml
Relates to #525
Fixes https://github.com/ericcornelissen/shescape/actions/runs/3433825413
---
The workflow uses `sudo` to install Zsh for fuzzing, so `disable-sudo` can't be enabled.
> Allow `sudo` for reusable-fuzz workflow

- .github/workflows/release.yml
Closes #426
---
[`ncipollo/release-action`](https://github.com/ncipollo/release-action) is one of the alternatives listed by [`actions/create-release`](https://github.com/actions/create-release) that is: actively maintained, runs on Node.js v16 depends on `@actions/core` `^1.10.0`, and has a similar input schema.
> Replace `actions/create-release` by `ncipollo/release-action`

- .github/codecov.yml
- .github/workflows/checks.yml
Followup to #576
---
Update the Codecov configuration and integration and e2e CI jobs to 1) fix the coverage reports for per-OS tests and 2) ensure coverage is maintained when the OS runner image is updated.
> Update Codecov coverage flags for integration and e2e tests

- .github/workflows/checks.yml
- .tool-versions
Relates to #583
---
Create a `.tool-versions` file with currently untracked dependencies (that we want to track). This file is first a configuration format for [asdf], but is also human-readable and thus can be used to know and track what versions of dependencies _should_ be used.
[asdf]: https://asdf-vm.com/
> Add `.tool-versions`

- .tool-versions
Relates to #583, #589
Bump ShellCheck to the latest available stable version as of this commit.
> Bump ShellCheck from v0.8.0 to v0.9.0

- src/main.js
- src/unix.js
- src/win.js
- test/bench/bench.js
- test/unit/_macros.js
- test/unit/main/escape.test.js
- test/unit/main/quote.test.js
- test/unit/unix/escape.test.js
Relates to #346, #452
Combine the `interpolation` and `quoted` arguments into an `options` argument to make options more explicit and make adding more options more maintainable by avoiding many positional boolean arguments which may be confused with one-another.
> Refactor `escapeArg` function signature (internal)

- .github/workflows/fuzz-matrix.js
- CONTRIBUTING.md
- test/fuzz/_common.cjs
- test/fuzz/exec-file.test.cjs
- test/fuzz/exec.test.cjs
- test/fuzz/fork.test.cjs
- test/fuzz/spawn.test.cjs
Update the fuzz targets so that fuzzing with the default/system shell is explicit - that is to fuzz is to use either a specific shell or the system shell. This is in contrast to the current situation where the system shell is tested regardless of any configured shell.
> Make fuzzing with default shell explicit

- .github/workflows/release.yml
Following #628, update the release Pull Request's "Post-merge checklist" to include a checkbox for releasing to npm. Also, update the copy to omit the repeated leading word "Verify".
> Update the release Pull Request "Post-merge checklist"

- src/unix.js
- src/win.js
- test/fuzz/_common.cjs
Update escaping for Bash, Dash, PowerShell, and Zsh to make it easier to understand how newlines (`\n` and `\r`) are escaped.
> Update and align newline replacements

- .github/workflows/reusable-fuzz.yml
Reduce the maximum number of active fuzz job to avoid all CI resources being consumed for fuzzing purposes.
Note: due to the usage of re-usable workflows this does not have an effect on the jobs created for pushing 91c1322289ca0348cbca4da986d4902190c3065f
Relevant docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel
> Set maximum number of fuzz jobs

- .github/workflows/checks.yml
To get some insight into what is being linted so this can be checked without having to run things locally.
As far as I was able to tell neither `markdownlint-cli` (`lint:md`) nor `shellcheck` (`lint:sh`) offer a verbose/debug mode.
> Enable verbose logging when linting in CI

- .github/workflows/nightly.yml
Relates to #613
Update the nightly workflow's tooling update job to automatically retry the flaky step of getting the latest available version of the tool using [`nick-fields/retry`]. Since the duration of this job doesn't matter much, and to be on the safe side, a timeout of 1 minute is configured to increase the probability of success.
Since the outputs of `nick-fields/retry` are restricted, the latest version is now stored as an environment variable.
[`nick-fields/retry`]: https://github.com/nick-fields/retry
> Reduce tooling update flakiness

- .shellcheckrc
- script/hooks/common.sh
- script/hooks/pre-commit
- script/hooks/pre-push
Relates to #392
Update the `.shellcheckrc` configuration to enable some "optional" checks that seem to have obvious benefits. Other "optional" checks may be enabled in the future.
> Enable (some) optional ShellCheck checks

- README.md
Move "Shells" back up in the documentation (it was moved down in cf1f7e3cf4f2ebf054fcaa642fa9a0fa43f7fcc2, though it's always been after "Usage"). The intent is to make it more prominent as it's pretty important to use a supported Shell. Move it under Features as the shells that are supported are features.
> Make the "Shells" section more prominent

- .github/workflows/nightly.yml
Relates to #667
- Use GitHub Application token to enable CI on tooling update Pull Requests.
- Add explicit Pull Request body. The default isn't empty but instead links to the Action used to create the Pull Request. Since this isn't helpful to the reader, we'll just mention the Pull Request was created automatically (similar to release Pull Requests) and what it changes.
> Update nightly tooling update workflow

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- README.md
- index.js
Update usage of the words "library" and "package" to be more consistent. The idea is that when talking about the code/API we're talking about the "library" and when we're talking about the thing that's published to npm it's a "package" (since it's the "Node _Package_ Manager").
> Consistently use "library" and "package"

- .github/workflows/publish.yml
Relates to #645, #671
Fix for the failure in https://github.com/ericcornelissen/shescape/actions/runs/3975149410
> Fix allowed endpoints for "Publish / GitHub" job

- package-lock.json
Update simple-git from 3.15.1 to 3.16.0 following a `npm audit` warning for <3.16.0 for CVE-2022-25860.
See also [the nightly run of Jan 27, 2023](https://github.com/ericcornelissen/shescape/actions/runs/4021189573).
> Bump transitive dependency simple-git

- src/unix.js
- src/win.js
- test/unit/unix/escape.test.js
- test/unit/unix/quote.test.js
- test/unit/win/escape.test.js
- test/unit/win/quote.test.js
Avoid explicitly returning `null` when an (implicit) `undefined` return value does just fine.
> Refactor `unix.js` and `win.js`

- test/fuzz/exec-file.test.cjs
- test/fuzz/exec.test.cjs
- test/fuzz/fork.test.cjs
- test/fuzz/spawn.test.cjs
Relates to #361, #688
Update fuzz targets in various ways:
- Refactor for performance. (169c9c66bd697e80df5e4a9892b3ee2a667a5896)
- Refactor for improved readability. (343c9db4e7eb5234743c964cf220969719c63b03)
- Handle errors explicitly. (eb57fe4502be99eddbe7a6d6d6fd4e52416f4bd6)
- Test non-sync versions of `execFileSync`, `execSync`, and `spawnSync`. (ccdc4b605ca9a12172b80b695f42306ef245231d)
- Don't test multiple args. (5ab274048281fab3a74e44702c32f7db4c24e4d8)
> Update fuzz targets

- .github/workflows/reusable-audit.yml
Relates to #317
Update the "Audit / Secrets" job configuration. These changes follow [this GitHub blog post](https://github.blog/changelog/2023-01-31-github-actions-job-summary-updates/) which says:
> [...] need to ensure machines have appropriate network access to communicate with the GitHub hosts below so that job summaries and logs emitted from Actions workflows can work as expected.
>
> - `actions-results-receiver-production.githubapp.com`
> - [...]
> Update "Audit / Secrets" job

- .github/workflows/release.yml
Relates to #621, #734 
Prevent shell injection in this workflow by capturing the update type as an environment variable and using the environment variable. This way, the expansion of the input in the command can't result in shell injection, whereas before a `'` in the input could unquote the current argument and something like `&&` could start a new command.
> Harden `release.yml` workflow

- .github/workflows/checks.yml
- .github/workflows/configs.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/reusable-audit.yml
- .github/workflows/reusable-fuzz.yml
Relates to #699
Add a new allowed endpoint to every CI egress policy in this project. The added endpoint is a standard endpoint used by GitHub Actions.
Also configure [the egress policy for the "Config / `package.json`" job](https://github.com/ericcornelissen/shescape/blob/653070b03510caa1ccf5bd094b572415e6c20be6/.github/workflows/configs.yml#L40-L44).
> Update all CI egress policies

- .github/workflows/checks.yml
Add `objects.githubusercontent.com:443` to the allowed endpoints of the egress policy for the "Checks / CodeQL" job. This follows unexpected failures in that job (i.e. without any changes) when it attempted to (re-)download CodeQL. Since this endpoint is already allowed for various other jobs, adding it is considered a non-issue.
> Update egress policy for the CodeQL job

- .npmignore
- .unimportedrc.json
- package.json
- rollup.config.js
- test/unit/testing/simple.test.js
- testing.js
Relates to #710
Consolidate all entrypoints in the root of the project for consistency and clarity.
> Move `testing.js` to root

- .github/workflows/checks.yml
Relates to #734
Update the "Check / Semgrep" job to have Semgrep generate an output in [SARIF](https://sarifweb.azurewebsites.net/) format and upload that to GitHub using [`github/codeql-action/upload-sarif`](https://github.com/github/codeql-action). See also the [relevant GitHub documentation](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github) as well as the [Semgrep CLI documentation](https://semgrep.dev/docs/cli-reference/).
> Generate and upload Semgrep SARIF report

- .github/workflows/checks.yml
Relates to #772, #774
... since it doesn't have the access to the secret, it can't run _and_ (as a result) will fail because it can't upload the SARIF file.
> Don't run Semgrep for PRs by dependabot

- script/hooks/pre-commit
Relates to #128
Update the pre-commit hook to format before stashing. This has the effect of avoiding stash-merge conflicts due to the stash pop at the end of the hook in some cases. This is considered not harmful as, eventually, all code (staged or not) must be formatted.
> Pre-format in pre-commit hook

- .github/workflows/checks.yml
Relates to #734, #772
Only make the `SEMGREP_APP_TOKEN` available in the job step that needs it, as opposed to the whole job. Following the principle of least privilege.
> Reduce availability scope of the `SEMGREP_APP_TOKEN` secret

- .github/workflows/checks.yml
Closes #773
Add a comment with an explanation for the reason of any elevated permissions in GitHub Actions workflows where it was not already present.
> Document reasons for elevated permissions

- .github/workflows/checks.yml
Relates to #734, #785, #788
Add a new CI job that runs the SAST tool [njsscan (GitHub Action)](https://github.com/ajinabraham/njsscan-action) ([njsscan](https://github.com/ajinabraham/njsscan)). This is a tool that is a:
> Static security code scanner (SAST) for Node.js applications powered by libsast and semgrep.
The Action is based on a tool with the same name: njsscan[2]. This is also available as a CLI (not tried as of this commit). The tool is aimed at scanning Node.js code specifically.
This is mainly intended as a test for the tool, as found in GitHub's "Choose aw workflow" UI for security.
~~Yes, this project already uses [Semgrep](https://semgrep.dev/), but not [libsast](https://github.com/ajinabraham/libsast) so it's considered worth trying just for that reason. Perhaps in the …
> Set up continuous SAST with njsscan

- .github/workflows/labeler.yml
Relates to #798, #799
- Configure `harden-runner` for the labeling job ([ref](https://github.com/ericcornelissen/shescape/pull/798#discussion_r1161164965)).
- Try to configure it to not remove pre-assigned labels (as seen in #799).
> Update the "Labeler / Label" job

- .github/workflows/checks.yml
Relates to #734, #785, #788, #793, #796
Add a new CI job to continuously run [Trivy](https://github.com/aquasecurity/trivy) using the official [Trivy Action](https://github.com/aquasecurity/trivy-action).
Trivy provides SBOM generation, known vulnerability scanning, infrastucture as code misconfiguration detection, secrets detection, and license detection and compliance. Here, vulnerability scanning and secrets detection are enabled. IaC not because this project has none. License scanning not because it requires configuration (and this project already uses licensee for this topic). And yes, secret scanning is already done [with gitleaks](https://github.com/ericcornelissen/shescape/blob/ff92fff6a825c3e6439d8ffc8f60937a4bb9714a/.github/workflows/reusable-audit.yml#L52-L88) and vulnerability …
> Set up continuous scanning with Trivy

- .github/workflows/ossf.yml
Relates to #802
Update the "OSSF / Scorecard" job with a new egress policy following a [failed run](https://github.com/ericcornelissen/shescape/actions/runs/4657972447) on the `main` branch.
> Update egress policy for "OSSF / Scorecard" job

- .licensee.json
- package-lock.json
Try out a new tool I created, [npm-updatedt], to update all transitive dependencies of this projects devDependencies.
Note: `scss-parser@1.0.6` has the same license text as `scss-parser@1.0.5`, it is found in the README.
[npm-updatedt]: https://github.com/ericcornelissen/npm-updatedt
> Update transitive (dev)dependencies

- .github/workflows/publish.yml
Relates to #559
Update the CI-based publishing strategy for this project to use the new `--provenance` option - setup based on the [official npm docs on the provenance](https://docs.npmjs.com/generating-provenance-statements).
The goal here is to increase linkability between the npm package and the GitHub repository as well as the specific commit and CI workflow that resulted in a specific version.
> Publish with provenance from CI

- .github/workflows/publish.yml
Relates to #824
Allow downloading Node.js in "Publish / Check".
All jobs that install Node.js were checked to include this endpoint in their egress policy.
> Update "Publish / Check" job

- CHANGELOG.md
- package.json
Update the [homepage for the package](https://github.com/ericcornelissen/shescape/blob/5d1de2a868d6f6c41108c23dbb085be6a63b6b42/package.json#L5). The old URL is for a GitHub Pages page that has been offline for a while now. Instead, just refer to the project README as a homepage.
> Update metadata homepage

- .github/workflows/checks.yml
- README.md
- stryker.config.js
Closes #777
Relates to #117
Remove the use of the Stryker Dashboard. In the CI, replace this by uploading the report as artifact so that it isn't necessary to rerun mutation tests locally to reproduce the report.
> Stop using Stryker Dashboard

- .github/workflows/nightly.yml
Relates to #613
Reverts #643
Remove the usage of `nick-fields/retry` from the nightly tooling job. It was put in place to avoid flakiness but does not succeed at it. As such, this is currently just an unnecessary dependency.
> Update nightly tooling job

- .github/codecov.yml
- .github/workflows/checks.yml
Supersedes #840
Remove end-to-end test coverage from the Codecov configuration file and stop uploading coverage data for the end-to-end tests to Codecov. This follows from observed errors in the Codecov dashboard, following <https://docs.codecov.com/docs/error-reference> it seems this is due to the fact that the end-to-end tests report coverage on generated files exclusively.
> Stop uploading coverage of end-to-end tests to Codecov

- package-lock.json
Bump `eslint-plugin-yml`>`yaml-eslint-parser`>`yaml` from v2.2.1 to v2.2.2 given GHSA-f9xv-q969-pqx4
> Bump transitive dependency `yaml`

- CONTRIBUTING.md
- README.md
- docs/api.md
- docs/recipes.md
- docs/testing.md
- docs/tips.md
Relates to #789
Make documentation text available under CC BY-SA 4.0 and snippets under the MIT license (like most tests and scripts).
> Add explicit license for documentation and snippets

- .github/workflows/checks.yml
Relates to #472
The artifact is only intended for re-use across jobs. As such, it can be deleted as soon as the workflow ends/possible.
See also [the `actions/upload-artifact` docs on Retention Period](https://github.com/actions/upload-artifact/tree/65d862660abb392b8c4a3d1195a2108db131dd05#retention-period).
> Set `retention-days` for the index-common-js artifact

- .github/workflows/checks.yml
Relates to #838
Make downloading the mutation report more convenient by making the name unique as well as identifiable from one run to the next. The commit SHA will be unique (otherwise git breaks) and also allows the user to relate the report to a particular commit, thus providing additional context on any mutants found.
> Improve mutation report artifact

- CONTRIBUTING.md
- README.md
- docs/api.md
- docs/recipes.md
- docs/testing.md
- docs/tips.md
Relates to #852
Change the link text for the MIT license from "MIT" to "MIT license" as _"MIT"_ could just as easily refer to MIT the institute.
> Improve link text for the MIT license

- .github/workflows/reusable-fuzz.yml
Relates to  #854
Include commit SHA in fuzz crash artifact to aid with reproducibility. Downloading the artifact will now tell you what commit the crash occurred at.
> Include commit SHA in fuzz crash artifact

- .github/workflows/checks-windows.yml
- .github/workflows/reusable-fuzz.yml
Relates to #862, #864
Addresses failure in CI run <https://github.com/ericcornelissen/shescape/actions/runs/4883357188>
Use `shell: bash` to ["Get git context"](https://github.com/ericcornelissen/shescape/blob/2105379debd9adc8c0e8ad04734ab732c5e1aa9f/.github/workflows/reusable-fuzz.yml#L69-L73), otherwise the step fails as the syntax being used isn't supported by PowerShell.
> Use `shell: bash` in reusable fuzz workflow for Windows support

- .eslintrc.yml
- .github/labeler.yml
- CONTRIBUTING.md
- bench/bench.js
- package.json
Relates to #273, #798
Move benchmarking code out of the testing directory and into a new top-level directory dedicated to benchmarking called 'bench'. Also use this change to add a new rule to the Labeler Action for automatically assigning the "benchmark" label.
> Separate benchmarking from testing

- src/unix.js
Relates to #373, #870
Update some of the replacement in Unix specific code to equivalent replacements that preserve more of the string (i.e. replace fewer characters).
This was reported by the [`regexp/prefer-lookaround`](https://ota-meshi.github.io/eslint-plugin-regexp/rules/prefer-lookaround.html) rule on #870. I haven't yet figured out why this problem isn't being reported by the [eslint-plugin-regexp](https://github.com/ota-meshi/eslint-plugin-regexp) with the current implementation.
> Simplify replacements in accordance with `regexp/prefer-lookaround`

- package.json
Relates to #135
Fix problems with the `format` and `format:check` commands not covering all files on all systems. The approach taken here is taken from [the Prettier docs](https://prettier.io/docs/en/install.html).
> Improve `format(:check)` command

- package-lock.json
Relates to #819, #892
I re-installed all direct dependencies. This had two effects:
- All transitive dependencies got updated.
- All integrity checks are now SHA512 (previously some were SHA1 which is potentially problematic)
This follows #892, which made [DevSkim](https://github.com/Microsoft/DevSkim) report all instances of SHA1 hashes in the `package-lock.json`.
> Update transitive dependencies and their integrity values

- .github/workflows/checks.yml
Relates to #788, #892, #898
Drop the CI job that runs DevSkim. While it did serve up some useful results (notably the SHA1 integrity values in `package-lock.json`), it comes with even more false positives. As a result, it's more noisy than useful in a continuous setting.
> Remove DevSkim analysis

- CHANGELOG.md
- docs/testing.md
- test/e2e/_.js
- test/e2e/child_process.test.js
- testing.js
Relates to #710
Include an exported value in the `shescape/testing` module that is a list of example shell injection strings for use in testing to get limited guarantee that shell injection is not possible.
> Provide injection strings for testing purposes

- bench/bench.js
- bench/unix.js
- bench/win.js
- src/main.js
- src/unix/bash.js
- src/unix/csh.js
- src/unix/dash.js
- src/unix/index.js
- src/unix/zsh.js
- src/win/cmd.js
- src/win/index.js
- src/win/powershell.js
- test/fixtures/unix.js
- test/fixtures/win.js
- test/integration/_macros.js
- test/unit/_macros.js
- test/unit/main/escape.test.js
- test/unit/main/quote.test.js
- test/unit/unix/csh.test.js
- test/unit/unix/facade.test.js
- test/unit/unix/index.test.js
- test/unit/unix/shells.test.js
- test/unit/win/facade.test.js
- test/unit/win/index.test.js
- test/unit/win/shells.test.js
Relates to #856, #870
Refactoring to simplify and optimize the internal flow of calling `shescape.quote()` or `shescape.quoteAll()`. Before this would partly involve the flow for `shescape.escape()`/`shescape.escapeAll()`, complicating that flow and making the quoting flow harder to understand. This separates the two flows, simplifying both (making them easier to understand) and actually improving performance slightly by having fewer conditions.
Somewhat incidentally, this also improves the test fixtures when it comes to quoting. Previously the implicit expected quoted value was the `noInterpolation` one. Now this is more explicit (for relevant input characters).
> Refactor internal logic for escaping strings when using `quote(All)`

- .github/workflows/checks.yml
- package.json
Relates to #199
Update how compatibility tests are run to use the earliest supported release instead of the latest available release for any given major version of Node.js. This aligns compatibility testing for all supported versions (previously testing was different between `10.13.0` and anything `>12`).
Compatibility testing was first introduced in #199 without a motivation for the specified versions. At this point in time I think it makes more sense to test the earliest stated supported versions and rely on Node.js for not introducing breaking changes for each major version.
> Run compatibility test on lowest supported version

- src/unix/index.js
- src/win/index.js
Refactor to simplify the platform-specific modules by using Node.js' `path(.win32).basename` functionality directly. The abstraction serves no purpose (anymore).
> Simplify getting the shell path's basename for every platform

- src/unix/index.js
- src/win/index.js
Followup to #919
Relates to #870
Remove the exporting of shell names internally as they are no longer used by the facades and should never be used otherwise.
> Internally unexport shell names

- .github/workflows/checks-unix.yml
- .github/workflows/checks-windows.yml
Relates to #870, #919
Following internal refactoring of platform specific code - including changes to files - update the path filters for Unix and Windows continuous integration workflows.
> Fix Unix and Windows CI triggers

- docs/api.md
Relates to #612
Complements #908
Update the [API docs](https://github.com/ericcornelissen/shescape/blob/e252256a2f2ac181b13d1382f0a30c20b6c46389/docs/api.md) to include documentation on the `options`. Before, these were just mentioned in the document but not explained so this adds explanation for each available option.
> Add docs about `options` to the API docs

- .github/workflows/checks-unix.yml
- .github/workflows/checks-windows.yml
- bench/bench.js
- bench/unix.js
- bench/win.js
- src/platforms.js
- src/unix.js
- src/win.js
- test/unit/platforms/get-helpers.test.js
- test/unit/unix/index.test.js
- test/unit/win/index.test.js
Relates to #870,  #919
Remove the `src/{unix,win}/index.js` (barrel) files in favor of (the re-introduction of) `src/{unix,win}.js`.
> Drop the barrel files and move back to `src/{unix,win}.js`

- src/main.js
- src/reflection.js
- test/_constants.cjs
- test/unit/main/escape.test.js
- test/unit/main/quote.test.js
Relates to #856, #948
In most cases provided arguments should be strings. So, reward providing strings with slightly better performance in the form of fewer conditions - at the cost of more conditions for non-string values.
> Reward providing arguments as strings

- .github/workflows/nightly.yml
Closes #649
Relates to #952, #953, #954
Remove tool matrix for nightly tooling updates job because it is no longer necessary with [`ericcornelissen/tool-versions-update-action`](https://github.com/ericcornelissen/tool-versions-update-action).
> Remove tool matrix for nightly tooling updates job

- test/unit/win/_expressions.js
Relates to #908
Update the expression for generating test strings that shouldn't be considered flags by the PowerShell flag protection logic to avoid generating strings starting with "`-".
> Fix flaky PowerShell unit test

- src/unix/csh.js
Relates to #659, #870
Explicit imports are preferred over using globals as it makes it explicit what is being used, improving understandability by reducing the need to guess.
> Re-introduce explicit import for `TextEncoder`

- test/unit/reflection/_.js
- test/unit/reflection/checked-to-string.test.js
- test/unit/reflection/is-string.test.js
- test/unit/reflection/to-array-if-necessary.test.js
Relates to #710
Add a new suite of unit tests targeting [`src/reflection.js`](https://github.com/ericcornelissen/shescape/blob/74ed727a4b1b39525807f8b502c895b6bd6e4f10/src/reflection.js) directly. Previously, this code was covered by unit tests almost entirely by the [suite for `main.js`](https://github.com/ericcornelissen/shescape/tree/74ed727a4b1b39525807f8b502c895b6bd6e4f10/test/unit/main).
> Add unit tests covering reflection functionality directly

- rollup.config.js
Relates to #161, #199, #308, #659, #965
Update the Rollup configuration by cleaning up the list of external modules to exclude unused modules.
> Clean up the list of externals in Rollup configuration

- CHANGELOG.md
- index.d.ts
- index.js
Quotes are shell specific, not necessarily the same for all shells for a given OS.
> Correction to the documentation for quoting functions

- CHANGELOG.md
- src/win/cmd.js
- test/fixtures/win.js
- test/fuzz/_common.cjs
- testing.js
Relates to #976
Improve testing w.r.t. protection against injection of environment variables. Fix a bug uncovered by these new tests in escaping for CMD, which did not cover escaping for environment variables before this Pull Request.
As of this Pull Request the escaping of environment variables when using `quote(All)` is not perfect in that it adds unexpected characters to the string received by the target program. A solution for this was not found in time, but pushing out any solution for the environment variables bug is seen as more important.
> Test coverage for environment variables

- CHANGELOG.md
- src/win/powershell.js
- test/fixtures/win.js
Relates to #983
The escape logic for PowerShell with `{interpolation:false}` (not quote) would escape "$" as "{backtick}$" and "{backtick}" as "{backtick}{backtick}". Both of these escapings are unnecessary for legitimate use cases and would lead to the exact value "{backtick}$" resp. "{backtick}{backtick}" being received by the invoked program.
> Update escaping for PowerShell with `{interpolation:false}`

- CHANGELOG.md
- src/win/powershell.js
- test/fixtures/win.js
Relates to #976, #982, #984
The quoting implementation for PowerShell incorrectly used double quotes which, like most Unix Shells, allows for string interpolation - i.e. `"$Env:PATH"` would expand the PATH environment variable whereas `'$Env:PATH'` would not. Hence, PowerShell quoting should be using single quotes to prevent interpolation. Tests have been updated accordingly.
~~The effects of this are TBD because it looks like [the escaping logic when quoting](https://github.com/ericcornelissen/shescape/blob/bfd88e7ffbfb75eee1236194ff9025be032d48d1/src/win/powershell.js#L61-L68) did account for this. The tests being added in #982 support this.~~ As far as I can tell this change does not have security or behavioral implication and does not fix any bugs. It is an improvement in two ways: 1) …
> Use single quotes when quoting for PowerShell

- .github/workflows/audit.yml
- .github/workflows/checks.yml
Separate the continuous audit job from the general checks workflow. The motivation for this is that checks should always pass (similar to `npm run verify`), but audit may not always be passing and this is not always a problem.
One place where this has an immediate impact is the build status badge in the README, which will no longer show as failing when the audit job is failing.
> Move CI auditing into separate workflow

- test/integration/escape-all.test.js
- test/integration/escape.test.js
- test/integration/quote-all.test.js
- test/integration/quote.test.js
Relates to #873
Remove the duplication of all integration tests for both the ESM and CJS version of the library in favor of testing the ESM version extensively. The motivation for this is to speed up integration tests and reduce unnecessary work.
> Reduce integration tests coverage of transpiled library

- .github/workflows/checks.yml
- .github/workflows/semgrep.yml
Relates to #734, #772, #775, #991
Separate the continuous Semgrep job from the general checks workflow. The motivation for this is that semgrep requires access to a secret to work, and this secret isn't available on Pull Requests from forks. This leads in a failed pipeline for external contributors, which is not desired. Hence, just run it on main and address problems it finds separately.
> Move Semgrep into separate workflow

- .github/workflows/config-codecov.yml
- .github/workflows/config-npm.yml
Relates to #295, #673
Remove the general config validation CI workflow and replace it with more specific workflows. The aim is to trigger these workflows only when necessary and not, say, validate the Codecov configuration when `package.json` changed.
> Split config workflow into multiple workflows

- .nsprc
- package-lock.json
Upgrade the transitive dependency `optionator` coming in through ESLint to the latest available version in order to resolve a transitive dependency on the word-wrap package following CVE-2023-26115. Also ignore CVE-2023-26115 because it's still in the dependency tree through jsfuzz (see [jsfuzz Merge Request 19](https://gitlab.com/gitlab-org/security-products/analyzers/fuzzers/jsfuzz/-/merge_requests/19) for more that), which isn't really a problem for this vulnerability.
> Resolve CVE-2023-26115

- .depcheckrc.yml
- .github/workflows/checks-unix.yml
- .github/workflows/checks-windows.yml
- .github/workflows/checks.yml
- .github/workflows/config-npm.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/reusable-audit.yml
- .github/workflows/reusable-fuzz.yml
- .npmrc
- package-lock.json
- package.json
- script/fuzz.js
Relates to #10
Replace `jsfuzz` with the `@gitlab-org/jsfuzz` in order to upgrade to the latest available version.
> Upgrade `jsfuzz`

- .github/workflows/reusable-fuzz.yml
Followup to #1004
With the switch from using `timeout` to using `--fuzzTime` the expected exit code for fuzzing (i.e. when there's no crash or other failure) changed to `0`.
> Update expected exit code when fuzzing in CI

- test/fixtures/unix.js
- test/fixtures/win.js
Update the test fixtures by:
- Normalizing titles, removing quotes from non-literal characters.
- Separating fixtures that test combination of characters into their own category.
- Using the same base 4 test cases for all categories.
Note: covered only `escape` and `quote` fixtures.
> Normalize test fixtures

- .github/workflows/checks.yml
- CHANGELOG.md
- index.js
- package.json
- rollup.config.js
- src/unix.js
- src/unix/csh.js
- src/win.js
Relates to #237
Update all imports of built-in modules in the library code to use `node:` protocol imports.
~~Currently on hold because it requires a higher minimum version than #963. Whether or not it makes sense to go with a slightly higher minimum version (`v14.17.0 -> v14.18.0`) _just_ for `node:` protocol imports is TBD. Perhaps the version has to be raised for a different reason, in which case this can be merged without further consideration.~~
I've decided to include this change in the v2.0.0 release because:
1. I'm pretty sure anyone using v14.17.0 could also be using v14.18.0 or higher. Even if non-trivial, I think anyone on a legacy version of Node.js should be prepared to make such adjustments.
2. If point 1 turns out to be wrong, this change can always be …
> Use `node:` protocol imports in library code

- index.js
- src/options.js
- test/unit/options/_.js
- test/unit/options/parse-options.test.js
Relates to #971
Refactor the source code to move the options parsing logic out of `index.js` and into a new module. This allows for unit test coverage of the logic, increasing confidence in correctness.
> Extract option parsing into a module

- .github/dependabot.yml
Configure one update group per the ["Grouped version updates for Dependabot public beta" blogpost](https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/) to streamline dependency updates by Dependabot.
This first group is aimed at the Stryker dependencies because those dependencies are always released together.
> Configure initial update groups for Dependabot

- CHANGELOG.md
- src/win/cmd.js
- test/fixtures/win.js
- test/fuzz/_common.cjs
Relates to #998
Update CMD escaping for `{ interpolation: true }` to work similar to escaping for quoting. This change is motivated by 1) the fact that it is used when quoting, and 2) that it removes the need for argument preparation when running e2e tests or fuzzing.
> Align escaping for interpolation with escaping for quoting for CMD

- docs/recipes.md
- index.d.ts
- index.js
- test/fuzz/exec.test.cjs
Relates to #1027
Update documentation as well as test code that relates to taking options intended for the `child_process` module and providing it to Shescape to move away from using the spread operator to assigning exactly and only what needs to be assigned.
> Update how `child_process` options should be given to Shescape

- script/fuzz.js
Update `script/fuzz.js` by omitting the unnecessary `shell: true` option.
> Remove `shell: true` from `script/fuzz.js`

- script/fuzz.js
Relates to https://github.com/ericcornelissen/shescape/pull/1052#issuecomment-1643310213
Use `npm-exec` to run jsfuzz & `npm.cmd` on Windows to spawn w/o shell.
> Fix `script/fuzz.js` for Windows

- .eslintrc.yml
- package-lock.json
- package.json
Relates to #537, #1049
Remove the dependency on [`eslint-plugin-json`] in favor of [`eslint-plugin-jsonc`]. There's a couple of motivations for this, most notably 1) it is more up-to-date (the former's last release was 2 years ago, the  latter's 1 month), and 2) it has support for `.jsonc` and `.json5`.
[`eslint-plugin-json`]: https://www.npmjs.com/package/eslint-plugin-json
[`eslint-plugin-jsonc`]: https://www.npmjs.com/package/eslint-plugin-jsonc
> Replace `eslint-plugin-json` by `eslint-plugin-jsonc`

- .github/labeler.yml
Relates to #798, #1006
Update [actions/labeler](https://github.com/actions/labeler) rules to:
1. Label Pull Requests touching fuzzing related files with the (new) [`fuzz` label](https://github.com/ericcornelissen/shescape/issues?q=label%3Afuzz), and
2. Not label fuzz tests using the [`test` label](https://github.com/ericcornelissen/shescape/issues?q=label%3Atest).
> Add labeler rules for `fuzz` label

- .knip.jsonc
Relates to #1049
See also [this comment on `0442cd9`](https://github.com/ericcornelissen/shescape/commit/0442cd9bfc471dae36112a69ab71b136f63b4f51#r122387796)
Update knip configuration by configuring its Stryker plugin rather than ignoring the Stryker configuration files. This conveniently allows for unignoring the dependency on `@stryker-mutator/tap-runner`.
> Update knip configuration

- test/e2e/_macros.js
- test/e2e/_runners.cjs
- test/fuzz/_common.cjs
- test/fuzz/exec-file.test.cjs
- test/fuzz/exec.test.cjs
- test/fuzz/fork.test.cjs
- test/fuzz/spawn.test.cjs
Extract the function that "run a test" against functions from the `node:child_process` API from the `test/fuzz` folder into a separate module that is more clearly intended for sharing (between e2e tests and fuzzing).
> Extract the test runners for `node:child_process`

- CONTRIBUTING.md
- script/fuzz.js
Relates to #1039
Update the fuzz script to, on completion, rename the generated coverage file so that it's unique to the target and shell that was fuzzed. This results in maintaining coverage data from previous runs. In turn, using nyc to generate a HTML coverage report will combine all coverage files into one report, giving a more holistic view of fuzz coverage.
One _limitation_ here is that the implementation distinguishes between fuzzing `cp.fork` using different shells, even though the shell is irrelevant when fuzzing `fork` (since it doesn't have a `shell` option).
> Improve use of fuzz coverage data

- CONTRIBUTING.md
- script/fuzz.js
Relates to #1039
Update the `fuzz.js` script to consider the `FUZZ_TIME` environment variable as a secondary source for the fuzz duration in seconds. Use the static `dotenv/config` import to make sure a `FUZZ_TIME` value set in `.env` will be used.
Also document the availability of fuzz time options in the Contributing Guidelines (missing before).
> Improve fuzz time support

- test/_runners.cjs
- test/e2e/_macros.js
- test/fuzz/_.cjs
- test/fuzz/exec-file.test.cjs
- test/fuzz/exec.test.cjs
- test/fuzz/fork.test.cjs
- test/fuzz/spawn.test.cjs
- test/integration/escape-all.test.js
- test/integration/escape.test.js
- test/integration/quote-all.test.js
- test/integration/quote.test.js
- test/integration/testing.test.js
- test/unit/unix/index.test.js
- test/unit/win/index.test.js
Relates to #1060, #1065
Improve various aspects of this project's tests by refactoring them.
- Update tests that import at the package level (i.e. they want to import `index.js` or `testing.js`) to import using the package name - i.e. like how end-users would import.
- Parameterize some tests for `src/{unix,win}.js`.
- Reorganize `_runners.cjs`.
- Reorganize imports in fuzz targets.
> Improve tests through refactoring

- package.json
Relates to #1066
1. Extend the `npm run verify` command to run all tests levels.
2. Make the `npm run verify` command run tests with coverage.
> Run all test levels in verify command

- src/executables.js
- test/unit/executables/resolve.test.js
Relates to #159
Remove input validation of the provided `deps` from the internal `resolveExecutable` function. This input validation isn't needed because the function is only used internally and if it isn't provided this should be caught by a test or similar, not an unhelpful runtime check which unnecessarily impacts performance.
> Remove input validation from `resolveExecutable`

- .github/codecov.yml
Relates to #766, #841
Following 22356528fd252f0d9fa7acd849fc6f40517a0915 this removes the transpiled module files from the Codecov flag configuration for integration tests as such generated files are ignored by Codecov.
Also include `testing.js` file in Codecov configuration
> Update Codecov configuration

- .github/codeql.yml
Relates to 61f25a1df0213bf44f66b51c554b2c85a958ec9d, #134, #766
Include [`testing.js`](https://github.com/ericcornelissen/shescape/blob/d256d6d8df1fde1a91a6b5785883190f406b5910/testing.js) in the CodeQL analysis.
> Make CodeQL scan `testing.js`

- .eslintrc.yml
- .github/workflows/checks.yml
- .gitignore
- .licensee.json
- .npmignore
- CHANGELOG.md
- package-lock.json
- package.json
- script/clean.js
- testing.d.ts
Closes #1084
Relates to #1082
Add [AreTheTypesWrong (attw)](https://arethetypeswrong.github.io/) CLI to continuously validate package types.
> Add AreTheTypesWrong (attw) CLI to continuously validate package types

- src/unix/bash.js
- src/unix/csh.js
- src/unix/dash.js
- src/unix/zsh.js
- src/win/powershell.js
Relates to #913
Remove unnecessary character escape from dash. The character "\n" does not need to be escaped because it's replaced by a " " three lines prior.
> Refactor argument replacement chains

- CHANGELOG.md
- src/unix/csh.js
- src/win/cmd.js
- test/_runners.cjs
- test/fixtures/unix.js
- test/fixtures/win.js
Relates to #1092
Update escaping for Csh and CMD to escape CR by removing it (instead of replacing by ` `) when necessary. This aligns the behavior for Csh and CMD with that of all other supported shells.
> Make CR escaping consistent across all shells

- docs/api.md
Relates to #612, #908
- Re-order functions alphabetically (I recall this order was originally chosen because I believed `quote(All)` was the "better" option, but it actually depends on what child_process function you use instead).
- Add additional note to the `flagProtection` option to disable it if the program invoked does not use standard flags, and (crucially) to add custom sanitization for it.
> Update API documentation

- test/integration/_generators.js
- test/integration/testing.test.js
- `testing.test.js`: Assert errored also when stubscape didn't error to avoid potential false positives if it also returns `undefined` values.
- `_generators.js`: Use common Windows detection logic instead of custom/local Windows detection logic.
> Improve integration tests

- README.md
Relates to #852
Update the README.md to replace the "footer" with license information about the file itself with a "License" section covering both the source code license and file(/documentation) license. This aims to improve discoverability of the license information.
> Update license information in `README.md`

- src/reflection.js
- test/e2e/_macros.js
Update all incorrectly formatted instances of type unions in JSDoc.
> Format type unions in JSDoc consistently

- .github/workflows/publish.yml
- .github/workflows/reusable-fuzz.yml
Relates to #317, #395, #401, #735
Update workflows based on [the blog post "Four tips to keep your GitHub Actions workflows secure"](https://github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure). Review was done manually.
> Harden CI workflow against shell/script injection

- src/options.js
- src/unix.js
- src/win.js
- test/unit/options/parse-options.test.js
- test/unit/unix/index.test.js
- test/unit/unix/no-shell.test.js
- test/unit/unix/shells.test.js
- test/unit/win/index.test.js
- test/unit/win/no-shell.test.js
- test/unit/win/shells.test.js
Relates to #1067
Improve the inner workings of Shescape by avoiding the use of `null` to represent a meaningful value - the selection of 'no shell' - by a `Symbol`. A `Symbol` was chosen because it is unique, impossible to intersect with a real shell name (as opposed to a string), and meaningful (as opposed to `null`).
> Use a `Symbol` to represent 'no shell'

- index.js
- src/options.js
- test/integration/constructor.test.js
- test/unit/options/parse-options.test.js
Relates to #1067, #1125
Refactor the code related to checking if a shell is supported such that it can be unit tested. Improving testability as well as composibility. Also included some additional refactoring to simplify the interface of the `parseOptions` function (replacing the `process` input by just `env`).
> Make "shell not supported" unit testable

- docs/recipes.md
Relates to #155, #139, #1067
With v2, `shell` must always be truthy so the removed statement is a bit redundant. Instead, more direct language is introduced to indicate that doing this should really be a last resort.
> Adjust wording for usage of `escape` with `exec`

- .github/workflows/config-npm.yml
- package.json
Relates to #673, #1083
Since it's more about finding problems than stylistic things. Also, now it makes more sense to execute it "by default" when `npm run vet` is invoked. This also (unintentionally) fixes the [Formatting and Linting](https://github.com/ericcornelissen/shescape/blob/aa1e8273257a0e12bc9e3d3bd17586cd2b40c460/CONTRIBUTING.md#formatting-and-linting) section of the Contributing Guidelines.
> Change `package.json` "linting" to "vetting"

- index.d.ts
- index.js
Relates to #1130
Update the `@example`s in the JSDoc for the `Shescape` class to actually initialize, rather than call, `Shescape` (both `.js` and `.ts`). Also correct the type decleration for the `Shescape` class to be a class rather than an interface (that way the `constructor` makes sense).
> Correct initialization in examples & Shescape class type definition

- .github/workflows/fuzz-cmd.yml
- .github/workflows/fuzz-powershell.yml
- CHANGELOG.md
- test/_constants.cjs
- test/integration/_generators.js
- test/unit/win/index.test.js
Relates to #1125, #1137
Avoid future regressions by improving the test coverage of different ways that executables can be resolved on Windows.
> Improve executable resolution coverage for Windows

- .github/workflows/checks.yml
- .github/workflows/reusable-fuzz.yml
Relates to #854, #862, #864, #940
This was originally added in an attempt to make it easy to identify what commit and artifact was created for, however it's incorrect on Pull Requests and thus confusing. Removing this for now.
> Drop commit SHA from artifact IDs

- package.json
- script/create-d-cts.js
Relates to #1083
The command `cp` isn't (always) available on Windows. Creating the script is simple enough, and it reduces friction for contributors on Windows, so I think it's worth it.
> Use script to copy .d.ts files to .d.cts

- script/check-runtime-deps.js
Relates to #497, #963
Make the script with custom checks for runtime dependency exit with a non-zero exit code (aka fail) when any violations are found. This should help better ensure the check is adhered to as it will make CI fail.
> Exit with non-zero exit code when runtime dependency violations found

- package.json
Relates to #1140
Update the helper `_coverage` command to explicitly specify what files should be reported on for coverage. This follows observed coverage reporting for certain files that aren't of interest.
> Explicitly configure what to `--include` in coverage reports

- test/compat/index.test.cjs
The current assertions fail on Windows (because quoting no longer puts quotes at the start and end of the input for CMD), so they're updated in line with the assertions for corresponding integration tests.
> Update compatibility tests

- test/fuzz/fork.test.cjs
Relates to #963
Fork can't be run with a shell, so trying to fuzz it with a shell can be misleading. This changes the fuzz target to throw immediately if a non-falsy shell is configured to avoid such confusion.
> Disallow fuzzing fork with a shell

- .github/workflows/checks.yml
- .github/workflows/nightly.yml
- .github/workflows/reusable-fuzz.yml
Add an (experimental) job to the nightly workflow that will run tests after updating runtime dependencies to the latest available(&compatible) version using `npm update`. This is in an effort to ensure compatibility with runtime dependencies is true for the latest versions, while keeping compatibility with the oldest version.
---
> Create nightly job to test against latest dependency versions

- script/release/bump-changelog.js
Relates to #1160
Fix a mistake in the `bump-changelog.js` script. It's currently incorrect and failing due to a missing import.
> Fix `bump-changelog.js` script

- test/compat/index.test.js
Relates to #963
Update the compatibility tests to use:
1. No shell for escaping because this will work for all systems.
2. Use an explicit shell when quoting because the default system shell (chosen when `shell: true`) does not necessarily work as expected on MacOS. Hopefully, this configuration supports more systems out of the box.
> Change `shell` used for compatibility tests

- package.json
Based on [this blog post](https://github.blog/changelog/2023-09-27-block-npm-package-publishes-when-names-and-versions-dont-match-between-manifest-and-tarball-package-json/). The packages being published weren't incorrect perse, but this is just a simple improvement for correctness and ecosystem consistency.
> Apply `npm pkg fix`

- .eslintrc.yml
- script/_common.js
- script/maybe-run.js
Relates to #1228
Update the `maybe-run.js` script in line with the now published version https://gist.github.com/ericcornelissen/6253b63db8c6f6ec6a58cb4d36c8e989 adopted from the script originally created here.
> Update `maybe-run.js` script

- test/compat/_.js
- test/compat/index.test.js
- test/compat/testing.test.js
- testing.js
> Improve compatibility tests

- SECURITY.md
Relates to #906
Update the Security Policy to include a section on "what to report", which can be seen as a basic threat model.
> Add "What to Report" to the Security Policy

- test/breakage/index.test.js
- test/breakage/testing.test.js
Relates to #1233
Add breakage tests verifying that the `Shescape` and `Stubscape` constructors by themselves behave the same way between the development head and last released version.
This should improve confidence as without these tests there is a chance that the implementation is changed such that, e.g., on the development head the constructor throws where in the last version all methods would throw instead (which is a breaking change). By having a test dedicated to the constructor, the described scenario would be caught.
> Improve breakage tests

- test/unit/_macros.js
- test/unit/unix/shells.test.js
- test/unit/win/shells.test.js
Relates to #373, 552e8eab56861720b1d4e5474fb65741643358f9
Add general performance/ReDoS tests modeled after [`fast-check`'s blog post on the topic](https://fast-check.dev/blog/2023/10/05/finding-back-a-redos-vulnerability-in-zod/).
This complements the ReDoS regression tests (for Unix) in that these tests will only catch some ReDoS regression. In fact, based on testing, this project's ReDoS CVEs wouldn't have been caught by the tests being added here.
> Extend ReDoS testing with general performance tests for escaping logic

- .github/labeler.yml
- package-lock.json
- package.json
- test/breakage/testing.test.js
Relates to #1233, #1268
Update the breakage tests to run against v2.0.1. This keeps the breakage tests up-to-date and allows for unskipping all tests that either fixed bugs observable by the breakage tests or were for previously unreleased APIs.
> Update breakage tests to run against v2.0.1

- .github/workflows/checks.yml
- .gitignore
Create a new CI job that verifies builds (i.e. transpilation to CJS) are reproducible for this project. This job depends on the build (transpilation) job as the build shouldnt be expected to be reproducible if it doesn't work to begin with.
Reproducible builds simplify verifying the build was done correctly for, e.g., the published package.
> Add basic reproducible build job

- CHANGELOG.md
- script/run-platform-coverage.js
- src/options.js
- test/integration/constructor/_.js
- test/integration/constructor/_pollution.js
- test/integration/constructor/constructor.test.js
Add a test to check for non-own property access which could be manipulated by prototype pollution. Fix such accesses to check if it is an own property first.
Because this is standard Node.js behavior I consider this a hardening measure, not a security bugfix.
> Tests for non-own property access

- SECURITY.md
Relates to #1254, #1261
Update the what to report section of the Security Policy with:
- Removing the in my opinion currently unnecessary "threat model" string.
- Organizing things alphabetically.
- More items.
- Clarify what the scopes represent.
> Update the What to Report section of the Security Policy

- CHANGELOG.md
- src/executables.js
- src/options.js
- src/platforms.js
- src/reflection.js
- src/win.js
- test/unit/executables/resolve.test.js
- test/unit/platforms/get-helpers.test.js
- test/unit/reflection/has-own.test.js
- test/unit/win/index.test.js
Relates to #1280
Update the internals of the project to protect against the potential of polluted properties based on manual evaluation of the source code. Re-use the `hasOwn` function from `options.js` (moved to `reflection.js`) to achieve this.
- `executables.js`: Explicitly check that `PATH` (or `Path`) isn't being inherited. This is the most obvious place where this is necessary as the code already accounts for the potential of `PATH` being undefined.
- `platforms.js`: Safely get `OSTYPE` in case it isn't defined in order to avoid wrongly concluding the current system is a Windows system as a result of a polluted `OSTYPE` value.
- `win.js`: Safely get `ComSpec` in case it isn't defined (already taken into account as well) to avoid using a default shell defined by a polluted property. …
> Further harden against polluted properties

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- RELEASE.md
- SECURITY.md
- docs/api.md
- docs/recipes.md
- docs/testing.md
- docs/tips.md
- script/hooks/common.sh
- script/hooks/pre-commit
- script/hooks/pre-push
- testing.d.ts
Relates to #789, #852, #1116
Add more file-specific license details using the [SPDX license ID] standard. The primary goal is to cover files whose licensing was previously missing or ambiguous.
This follows the existing practice of defining explicitly the applicable license for all source code (including scripts and tests) as well as external facing documentation per file.
[SPDX license ID]: https://spdx.dev/learn/handling-license-info/
> Adopt more explicit licensing

- docs/testing.md
Relates to #1149
Remove an example from the Testing module involving `Throwscape` because the way it's used is incorrect.
> Update testing documentation w.r.t `Throwscape`

- .github/workflows/checks.yml
- .gitignore
Relates to #1279
Update the continuous reproducibility check to not just verify that the transpilation(/build) is reproducible, but the published package bits that go to the npm registry.
> Verify reproducibility of published package

- package-lock.json
- package.json
- test/unit/executables/resolve.test.js
- test/unit/platforms/get-helpers.test.js
- test/unit/win/index.test.js
Relates to #1334
Bump `@fast-check/ava` from 1.2.0 to 1.2.1 and partially revert 2a85be8c76ba97715ca2b43952f7070c6027f454 to again use `testProp` for property tests using `fc.pre`.
> Bump `@fast-check/ava` from 1.2.0 to 1.2.1

- test/compat/index.test.js
Relates to #1203
Fix the compatibility tests in some environments by allowing [the unsupported shell error](https://github.com/ericcornelissen/shescape/blob/e861d4256fc439efdd8bc044d179cb81cc563c3b/src/options.js#L24) in those tests. This error should be allowed because it does not indicate a compatibility problem.
> Allow unsupported shell error in compatibility tests

- .github/codecov.yml
- .github/workflows/checks.yml
Relates to #1130, #1343
Expand the usage of [Codecov](https://app.codecov.io/gh/ericcornelissen/shescape) to include tracking the breakage test coverage and compatibility test coverage over time.
> Track breakage and compatibility coverage with Codecov

- .github/workflows/config-npm.yml
- package-lock.json
- package.json
Relates to #673, #1083
Start vetting(/linting) the lockfile for problems. In particular, with the current configuration this checks that only listed sources are used for packages as well as that only `https` is used.
**Open question:** Can we automatically verify the lockfile is "in line" with the manifest. E.g. do the versions match and are there no extraneous packages?
> Use lockfile-lint to vet `package-lock.json`

- test/compat/stateless.test.js
Relates to #1130, #1351
Fix the compatibility tests for `stateless.js` in some environments by allowing [the unsupported shell error](https://github.com/ericcornelissen/shescape/blob/e861d4256fc439efdd8bc044d179cb81cc563c3b/src/options.js#L24) in those tests. This error should be allowed because it does not indicate a compatibility problem.
> Allow unsupported shell error in stateless.js compatibility tests

- README.md
- docs/migration.md
Relates to #963, #1130
Add a migration guide for upgrading from v1 to v2.
> Add migration guidelines for v1->v2 upgrade

- README.md
- config/eslint.yml
- script/_.js
- script/_common.js
- script/check-runtime-deps.js
- script/clean.js
- script/create-d-cts.js
- script/fuzz.js
- script/hooks/common.sh
- script/hooks/pre-commit
- script/hooks/pre-push
- script/release/bump-changelog.js
- script/release/bump-jsdoc.js
- script/release/get-release-notes.js
- script/run-platform-coverage.js
Relates to #789, #1298
Relicense scripts to remove the attribution requirement to make them easier to re-use.
> Remove attribution requirement from scripts

- RELEASE.md
Relates to #441
Update the manual Release Guidelines to include commands/options to avoid errors while executing the commands while following the steps.
When syncing the repository, dependencies must be installed because the helper scripts to bump the JSDoc and changelog need them. Similarly, ensure dependencies are installed when publishing because that's needed to be able to transpile. This is included separately because of the delay in between initiating the release and finally publishing (that is, the opening, and waiting for validation, of the release Pull Request).
> Improve manual Release Guidelines

- CONTRIBUTING.md
- RELEASE.md
- SECURITY.md
- docs/recipes.md
- docs/testing.md
- docs/tips.md
Closes #1340
Update the "alerts" present in the MarkDown documentation to move adopt a style that works independently of where it is rendered.
The previous format was an old variant of the GitHub flavored markdown syntax that created properly rendered alerts on GitHub. This syntax has changed since, however the new one is
1. Not as clear outside the context of GitHub, and
2. Not implemented correctly (it doesn't render correctly in all scenarios, e.g. it wouldn't render properly for the use case in the Release Guidelines).
Given those considerations, this adopts a semantically correct (no block quotes) and standard-markdown way to have alerts (i.e. text blocks that stand out from the rest of the text in some way).
> Redo alerts (i.e. notes and warnings) in the documentation

- test/integration/constructor/constructor.test.js
Shell should be a program that exists on any system that runs this test suite but not a shell that is actually supported. The Node.js binary should exist when this test suite is run, but should not be a shell that is supported.
This adds coverage for the `if (!isShellSupported(shellName))` branch in `src/internal/options.js` (and correspondingly the `unsupportedError` function).
> Integration test for "shell missing" and "shell unsupported"

- .github/workflows/checks.yml
- .github/workflows/publish.yml
- .npmrc
- CONTRIBUTING.md
- RELEASE.md
- package.json
Update the repository configuration to disable lifecycle scripts (such as installation scripts) by default. Adjust all current usage of such scripts to avoid relying on them and use alternatives instead.
> Disable `npm` lifecycle scripts by default

- test/_arbitraries.js
Relates to #1407
Update the `shescapeOptions` arbitrary to be able to generate options with either a missing shell `"not-actually-a-shell-that-exists"` or a shell that (should) exists but isn't supported `"node"`.
Note that the Node.js binary should exist when test are run, but should not be a shell that is supported by Shescape.
This ensures increased coverage in `src/internal/options.js` and `src/internal/executables.js`.
> Add "shell missing" and "shell unsupported" cases to arbitrary options

- package-lock.json
Ran `npm audit fix` to patch the vulnerability in package `ip`. The resolution is an update to an intermediate dependency which replaced `ip` by `ip-address`.
Because this dependency is only used in the development dependencies this update is not considered important for the project's security, especially users. Still updating makes sense.
> Fix vulnerability in package `ip`

- .github/workflows/checks.yml
Relates to #1489
Allow `api.codecov.io:443` for test job. Should address the warning currently emitted by the Codecov action:
> Test
> Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/c16abc29c95fcf9174b58eb7e1abf4c866893bc8/dist/codecov' failed with exit code 1
> Update egress policy for jobs using Codecov

- CHANGELOG.md
- src/modules/testing.d.ts
- src/modules/testing.js
- test/integration/testing/commonjs.test.js
- test/integration/testing/functional.test.js
Closes #1307
Relates to #1149
Expand the set of test stubs with one to simulate that using shescape to escape or quote fails.
> Create test stub that fails when used

- .github/workflows/secrets.yml
Relates to #403
Update the secret scanning workflow to replace gitleaks by trufflehog. This is motivated by the fact that gitleaks action is facing some technical difficulties that aren't being addressed.
> Replace gitleaks by trufflehog

- package-lock.json
- package.json
- test/unit/executables/resolve.test.js
- test/unit/platforms/get-helpers.test.js
- test/unit/win/index.test.js
Relates to #1610
Upgrade the pp-test-kit dependency and use the new simulate API in tests that test behavior under the effect of a specific polluted property.
> Upgrade to `pp-test-kit@0.1.2`

- .github/workflows/checks.yml
This removes the continuous integration with njsscan. The Action is a bit of a supply chain risk (unpinnable and potentially unmaintained) and has otherwise not been used (never received an alert from it). Additionally, per the description of #793, it seems to build on top of Semgrep which is already being used in this project too.
> Stop using njsscan

- .github/workflows/checks.yml
Relates to #797, #1617
This removes the continuous integration with Trivy. The Action is a bit of a supply chain risk (unpinnable) and has otherwise not been used (never received an alert from it). Also, as discussed in #797, it was intended as a test and does not seem to provide anything not covered by other integrations.
> Stop using Trivy

- package-lock.json
Relates to [Audit / npm (#1040)](https://github.com/ericcornelissen/shescape/actions/runs/10535239050)
Bump micromatch from 4.0.7 to 4.0.8 to resolve CVE-2024-4067
> Bump micromatch from 4.0.7 to 4.0.8

- .licensee.json
- package-lock.json
- package.json
Add [`ls-engines`](https://www.npmjs.com/package/ls-engines) as a dependency and use it as part of vetting (specifically the `vet:package.json` subcommand) to ensure that the engines.node range specified for this project is in line with all of its dependencies. That is, if the manifest claims the package is compatible with a Node.js version not supported by one of the (production or peer) dependencies, it will complain.
> Automatically validate the `engines.node` range using ls-engines

- .github/workflows/audit-dev.yml
- .github/workflows/audit-release.yml
- .github/workflows/checks.yml
- .github/workflows/config-npm.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/reusable-fuzz.yml
- .github/workflows/secrets.yml
- .github/workflows/semgrep.yml
Relates to #395, #401, #1114
Update all GitHub Actions workflows following an analysis by [`zizmor`](https://github.com/woodruffw/zizmor). In particular, this avoids persisting git credentials when the job does not need it, there's only one job that needs it which is the one that creates the git tag and updates the major version branch upon releases.
`zizmor` did have more concerns but these were not addressed, namely:
- Overly permissive `permissions: read-all`: I think this is okay, the project is entirely open so I don't see a risk of an attacker reading anything.
- Use of `pull_request_target: ~` in laberer.yml: as far as I'm aware this is the only way to have this setup work, and it does not run any untrusted code.
> Harden GitHub Actions workflows

- .github/workflows/audit-release.yml
Relates to #1762, [Audit (release) rule 428](https://github.com/ericcornelissen/shescape/actions/runs/11676998917), [Audit (release) 429](https://github.com/ericcornelissen/shescape/actions/runs/11696658986)
It was updated to use the new command for auditing runtime dependencies even though the latest release does not yet use this command. This should be updated with the next release.
> Revert recent change to `audit-release.yml`

- package-lock.json
- package.json
Relates to #1766
Replace `npm-run-all` with `npm-run-all2` because itThe latter is a fork of the former which is more up-to-date and still maintained.
> Replace `npm-run-all` with `npm-run-all2`

- .licensee.json
- package-lock.json
Update `npm-license-corrections` to the latest available version to benefit from the contributions I made for the licensee package exceptions present in this project, which have now been removed.
> Bump transitive dependency `npm-license-corrections`

- .ndmrc
Relates to #1805
The problem has been resolved at the level previously mentioned and is now blocked by an intermediate dependency.
I'm opening this as a placeholder, depending on when the linked PR is merged, this may be superceded by a version bump of `ava` instead.
> Update deprecation ignore reason for glob 7

- .github/workflows/checks.yml
- .github/workflows/fuzz-cmd.yml
- .github/workflows/fuzz-no-shell-win.yml
- .github/workflows/fuzz-powershell.yml
- .github/workflows/nightly.yml
Relates to #576, #1416
Supersedes #1825
Following <https://github.blog/changelog/2025-04-10-github-actions-macos-15-and-windows-2025-images-are-now-generally-available/>.
> Bump `runs-on:` values

- docs/tips.md
Relates to #1012, https://github.com/ericcornelissen/shescape/issues/2009#user-content-fn-1-7b66e55b443c54504bca43701930dbf0
Clarify what "without an explicit shell" means in the tips by rewording it to be more explicit in terms of implementation.
> Update "Prefer `execFile`, `fork`, or `spawn`" tip

- src/modules/index.js
Update the `Shescape` class to use actual [private fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties), instead of implied private fields through a naming convention.
According to MDN (link above) this language feature has been supported in Node.js since v14.6, which is before [our earliest supported version, v14.18.0](https://github.com/ericcornelissen/shescape/blob/322a4b25a828d4315396a1487c3636aac7adc1ab/package.json#L42). Hence, this should not cause compatibility issues for anyone (as confirmed by the compatibility tests).
Technically this is a breaking, but I'm inclined to ignore that as these fields should really not have been used in the first place. That being said, if there's push back after releasing I'd be willing to revert the …
> Use proper private fields

- README.md
- docs/LICENSE-CC-BY-SA-4.0
- docs/LICENSE-MIT-0
- docs/api.md
- docs/migration.md
- docs/recipes.md
- docs/testing.md
- docs/tips.md
- docs/use-cases.md
Add local copies of all licenses used to the project source code. This avoids problems in the future and makes it clearer what the intended license text is.
Also distribute code snippets more liberally under the MIT-0 instead of MIT license.
> Incorporate all license texts into the project

- .github/workflows/audit-dev.yml
- .github/workflows/audit-release.yml
- .github/workflows/checks.yml
- .github/workflows/gha.sum
- .github/workflows/labeler.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/reusable-fuzz.yml
Reverts #317
Drop the CI runtime protection offered by the harden-runner, triggered by the network access control being too unreliable and having caused to many problems over the years (this PR in particular due to recent failures of the [labeler job](https://github.com/ericcornelissen/shescape/actions/runs/15968172441)). Moreover, the protection is partial and therefor limited. In particular it does nothing for the Windows and macOS jobs, allowing easy bypass in practice, nor container-based jobs (e.g. Semgrep).
> Stop using `step-security/harden-runner`

- test/fixtures/unix.js
- test/fixtures/win.js
Relates to #2036
Omit unnecessary values from the test fixtures. In particular, without a shell (i.e. when shell is `null` in the fixtures) quoting arguments is not possible (see [`docs/api.md`](https://github.com/ericcornelissen/shescape/blob/b5afc4d39e54e4068f0697e746d80b11a250f950/docs/api.md?plain=1#L40C1-L41C32)).
> Minimize test fixtures

- script/clean.js
Closes #2070
This updates the clean.js script to:
1. Update the list of things to delete. In particular remove the `.nyc_output/` folder which isn't being created anymore for a long time and add the `.cache/` folder.
2. Add logging for a. what files and folders are actually being removed. b. when files or folder cannot be removed.
For me, this was an experiment in using Copilot.
> Improve `npm run clean` experience

- .github/workflows/audit-dev.yml
- config/dirty-waters.json
Relates to #1883
This disables a dirty-waters check and updates the ignores in accordance with [a recent dirty-waters report](https://github.com/ericcornelissen/shescape/actions/runs/16666050963/job/47172588980#step:4:3126). I'm not happy this is a separate Pull Request, I would've preferred these (latter) updates to co-occur with dependency updates...
I'm not 100% sure why `dirty-waters` didn't complain sooner. I vaguely remember it having some runtime errors leading it to be unable to comment the report on Pull Requests as a result of which I might have just ignored the necessary updates accidentally. However, there might also be something going on with its [`x_to_fail` option](https://github.com/chains-project/dirty-waters-action/blob/2a5212bf8abe0c97b77f6aa5de5eedb839efa637/action.yml# …
> Update dirty-waters configuration

- .github/workflows/audit-release.yml
- .github/workflows/gha.sum
Relates to #2045, #2115
Otherwise action checksum verification fails during execution of that job because of the mismatch between the workflow on main and the workflow on v2.
It does not appear to be possible to start the job from the v2 branch on a schedule ([`schedule:` docs](https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idruns-on)).
> Freeze release audit workflow's actions
